(() => {
'use strict';
const cfg=window.DDH_CONFIG||{},base=String(cfg.supabaseUrl||'').replace(/\/$/,''),key=String(cfg.supabasePublishableKey||''),SESSION_KEY='ddh_supabase_session';
const gate=document.querySelector('#adminGate'),app=document.querySelector('#adminApp'),queue=document.querySelector('#moderationQueue'),reports=document.querySelector('#reportQueue'),kpis=document.querySelector('#adminKpis');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(a,c)=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c||'USD'}).format(Number(a)||0)}catch{return `${c} ${a}`}};
const sess=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}};
const role=()=>{try{return JSON.parse(atob(String(sess()?.access_token||'').split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))?.app_metadata?.role||''}catch{return ''}};
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,{method='GET',body,prefer='return=representation'}={}){const s=sess();if(!s?.access_token)throw new Error('Sign in again.');const r=await fetch(`${base}${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>[]);if(!r.ok)throw new Error(data.message||data.error||`Request failed (${r.status})`);return data}
async function audit(action,listingId=null,reportId=null,note=null){const s=sess();await api('/rest/v1/moderation_actions',{method:'POST',body:{admin_id:s.user.id,listing_id:listingId,report_id:reportId,action,note},prefer:'return=minimal'})}
async function setListing(id,status,note){const body={status,moderation_note:note||null};if(status==='published')body.published_at=new Date().toISOString();await api(`/rest/v1/listings?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body,prefer:'return=minimal'});await audit(status==='published'?'approve_listing':'reject_listing',id,null,note||null);toast(status==='published'?'Listing approved.':'Listing rejected.');load()}
async function setReport(id,status){await api(`/rest/v1/reports?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{status,resolved_at:new Date().toISOString(),resolved_by:sess().user.id},prefer:'return=minimal'});await audit(`${status}_report`,null,id,null);toast('Report updated.');load()}
function renderListings(rows){if(!rows.length){queue.innerHTML='<div class="empty-inline">No listings are waiting for review.</div>';return}queue.innerHTML=rows.map(x=>`<article class="admin-row" data-listing="${esc(x.id)}"><div><span class="status-chip">${esc(x.status)}</span> ${x.price_flagged?'<span class="flag">Price flagged</span>':''}<h3>${esc(x.title)}</h3><p>${esc(x.category)} · ${esc(x.condition)} · ${esc(money(x.price_amount,x.price_currency))}</p><p>${esc(x.city||'Location not provided')} · ${esc(x.moderation_note||'No moderation note')}</p></div><div class="admin-actions"><input class="control admin-note" placeholder="Reason / note"><button class="btn blue small" data-approve>Approve</button><button class="btn secondary small" data-reject>Reject</button></div></article>`).join('');queue.querySelectorAll('[data-listing]').forEach(row=>{const id=row.dataset.listing,note=()=>row.querySelector('.admin-note').value.trim();row.querySelector('[data-approve]').onclick=()=>setListing(id,'published',note());row.querySelector('[data-reject]').onclick=()=>{if(!note())return toast('Add a rejection reason first.');setListing(id,'rejected',note())}})}
function renderReports(rows){if(!rows.length){reports.innerHTML='<div class="empty-inline">No open safety reports.</div>';return}reports.innerHTML=rows.map(x=>`<article class="admin-row" data-report="${esc(x.id)}"><div><span class="status-chip">${esc(x.reason.replaceAll('_',' '))}</span><h3>Report ${esc(x.id.slice(0,8))}</h3><p>${esc(x.details||'No additional details')}</p><p>Listing: ${esc(x.listing_id||'Not attached')} · ${new Date(x.created_at).toLocaleString()}</p></div><div class="admin-actions"><button class="btn blue small" data-resolve>Resolve</button><button class="btn secondary small" data-dismiss>Dismiss</button></div></article>`).join('');reports.querySelectorAll('[data-report]').forEach(row=>{const id=row.dataset.report;row.querySelector('[data-resolve]').onclick=()=>setReport(id,'resolved');row.querySelector('[data-dismiss]').onclick=()=>setReport(id,'dismissed')})}
async function load(){try{const [ls,rs]=await Promise.all([api('/rest/v1/listings?select=id,title,category,condition,price_amount,price_currency,city,status,price_flagged,moderation_note,created_at&status=in.(pending,rejected)&order=created_at.asc'),api('/rest/v1/reports?select=id,listing_id,reason,details,status,created_at&status=in.(open,reviewing)&order=created_at.asc')]);renderListings(ls);renderReports(rs);kpis.innerHTML=`<div class="admin-kpi"><span>Pending listings</span><strong>${ls.filter(x=>x.status==='pending').length}</strong></div><div class="admin-kpi"><span>Price flags</span><strong>${ls.filter(x=>x.price_flagged).length}</strong></div><div class="admin-kpi"><span>Open reports</span><strong>${rs.length}</strong></div>`}catch(err){gate.hidden=false;gate.textContent=err.message;app.hidden=true}}
if(role()!=='admin'){gate.hidden=false;app.hidden=true}else{gate.hidden=true;app.hidden=false;load()}
document.querySelector('#refreshAdmin')?.addEventListener('click',load);
})();