(() => {
  'use strict';
  const cfg=window.DDH_CONFIG||{};
  const url=String(cfg.supabaseUrl||'').replace(/\/$/,'');
  const key=String(cfg.supabasePublishableKey||'');
  const grid=document.querySelector('#marketplaceGrid');
  const empty=document.querySelector('#emptyState');
  const resultCount=document.querySelector('#resultCount');
  const filters=document.querySelector('#filters');
  const controls={search:document.querySelector('#searchInput'),category:document.querySelector('#categoryFilter'),brand:document.querySelector('#brandFilter'),condition:document.querySelector('#conditionFilter'),min:document.querySelector('#minPrice'),max:document.querySelector('#maxPrice'),location:document.querySelector('#locationFilter'),sort:document.querySelector('#sortFilter')};
  const params=new URLSearchParams(location.search);
  controls.search.value=params.get('q')||'';
  const requestedCategory=params.get('category');
  if(requestedCategory&&[...controls.category.options].some(o=>o.value===requestedCategory))controls.category.value=requestedCategory;
  controls.condition.value=params.get('condition')||'all';
  controls.min.value=params.get('min_price')||'';
  controls.max.value=params.get('max_price')||'';
  controls.location.value=params.get('location')||'';
  controls.sort.value=params.get('sort')||'newest';
  let rows=[];let images=new Map();let sellers=new Map();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=(amount,currency)=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD',maximumFractionDigits:4}).format(Number(amount)||0)}catch{return `${currency||'USD'} ${Number(amount||0).toLocaleString()}`}};
  const publicImage=path=>path?`${url}/storage/v1/object/public/listing-images/${String(path).split('/').map(encodeURIComponent).join('/')}`:'';const countryName=code=>window.DDH_COUNTRIES?.name?.(code)||code||'';
  async function get(path){const r=await fetch(`${url}${path}`,{headers:{apikey:key}});if(!r.ok)throw new Error(`Marketplace request failed (${r.status})`);return r.json()}
  function localAmount(item){const loc=window.DDH_LOCALIZATION;const converted=loc?.convertAmount?.(Number(item.price_amount),item.price_currency);return Number(converted?.amount??item.price_amount)||0}
  function matches(item){const q=controls.search.value.trim().toLowerCase();const category=controls.category.value;const brand=controls.brand.value;const cond=controls.condition.value;const locq=controls.location.value.trim().toLowerCase();const amount=localAmount(item);const min=Number(controls.min.value||0);const max=Number(controls.max.value||0);return(category==='all'||item.category===category)&&(brand==='all'||item.brand===brand)&&(cond==='all'||item.condition===cond)&&(!q||`${item.title} ${item.brand} ${item.model} ${item.category} ${item.storage||''}`.toLowerCase().includes(q))&&(!locq||`${item.city||''} ${item.country_code||''} ${countryName(item.country_code)}`.toLowerCase().includes(locq))&&(!min||amount>=min)&&(!max||amount<=max)}
  function card(item){const path=images.get(item.id);const seller=sellers.get(item.seller_id)||'Seller';const original=money(item.price_amount,item.price_currency);const place=[item.city,countryName(item.country_code)].filter(Boolean).join(', ');const localCurrency=window.DDH_LOCALIZATION?.state?.currency||'USD';const estimate=item.price_currency!==localCurrency?`<div class="converted-line">Local estimate: <span class="price local-estimate" data-price-amount="${esc(item.price_amount)}" data-price-currency="${esc(item.price_currency)}">${esc(original)}</span></div>`:'';const battery=item.specs?.battery_health?`<span class="pill">Battery ${esc(item.specs.battery_health)}</span>`:'';return `<a class="product-card" aria-label="${esc(item.title)}, ${esc(item.condition==='new'?'New':'Used')}, ${esc(original)}" data-id="${esc(item.id)}" data-listing-card href="/device.html?id=${encodeURIComponent(item.id)}"><div class="product-image">${path?`<img src="${esc(publicImage(path))}" alt="${esc(item.title)}" loading="lazy" width="800" height="600">`:'▯'}</div><div class="product-content"><div class="tag-row"><span>${esc(item.category)}</span><span class="pill">${esc(item.condition==='new'?'New':'Used')}</span></div><h3>${esc(item.title)}</h3><div class="subline">${esc(item.storage||'Details available')}${place?` · ${esc(place)}`:''}</div>${battery}<div class="seller-price-primary">${esc(original)}</div>${estimate}<div class="seller-line"><span>Listed by ${esc(seller)}</span></div></div></a>`}
  function syncUrl(){const p=new URLSearchParams();const q=controls.search.value.trim();if(q)p.set('q',q);if(controls.category.value!=='all')p.set('category',controls.category.value);if(controls.brand.value!=='all')p.set('brand',controls.brand.value);if(controls.condition.value!=='all')p.set('condition',controls.condition.value);if(controls.min.value)p.set('min_price',controls.min.value);if(controls.max.value)p.set('max_price',controls.max.value);if(controls.location.value.trim())p.set('location',controls.location.value.trim());if(controls.sort.value!=='newest')p.set('sort',controls.sort.value);history.replaceState(null,'',location.pathname+(p.toString()?'?'+p.toString():''))}
  function render(){syncUrl();let filtered=rows.filter(matches);if(controls.sort.value==='price-asc')filtered.sort((a,b)=>localAmount(a)-localAmount(b));else if(controls.sort.value==='price-desc')filtered.sort((a,b)=>localAmount(b)-localAmount(a));else filtered.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));grid.innerHTML=filtered.map(card).join('');empty.hidden=filtered.length>0;resultCount.textContent=`${filtered.length.toLocaleString()} device${filtered.length===1?'':'s'}`;window.DDH_LOCALIZATION?.refresh?.()}
  async function load(){try{await window.DDH_LOCALIZATION?.ready;const data=await get('/rest/v1/listings?select=id,slug,title,category,brand,model,condition,storage,city,country_code,price_amount,price_currency,seller_id,created_at,specs&status=eq.published&order=created_at.desc&limit=200');rows=data||[];const ids=rows.map(x=>x.id);const sellerIds=[...new Set(rows.map(x=>x.seller_id).filter(Boolean))];if(ids.length){const list=ids.map(x=>`\"${x}\"`).join(',');const imgs=await get(`/rest/v1/listing_images?select=listing_id,storage_path,variants,sort_order&listing_id=in.(${encodeURIComponent(list)})&order=sort_order.asc`).catch(()=>[]);for(const img of imgs){if(!images.has(img.listing_id))images.set(img.listing_id,img.variants?.card||img.storage_path)}}if(sellerIds.length){const list=sellerIds.map(x=>`\"${x}\"`).join(',');const profiles=await get(`/rest/v1/public_profiles?select=id,display_name&id=in.(${encodeURIComponent(list)})`).catch(()=>[]);sellers=new Map(profiles.map(x=>[x.id,x.display_name||'Seller']))}const brands=[...new Set(rows.map(x=>x.brand).filter(Boolean))].sort();controls.brand.innerHTML='<option value="all">All brands</option>'+brands.map(b=>`<option>${esc(b)}</option>`).join('');const requestedBrand=params.get('brand');if(requestedBrand&&brands.includes(requestedBrand))controls.brand.value=requestedBrand;render()}catch(err){resultCount.textContent='Marketplace unavailable';empty.hidden=false;empty.textContent=err.message}}
  let debounceTimer;Object.values(controls).forEach(c=>{if(!c)return;const evt=c.tagName==='INPUT'?'input':'change';c.addEventListener(evt,()=>{if(evt==='input'){clearTimeout(debounceTimer);debounceTimer=setTimeout(render,180)}else render()})});document.querySelector('#clearFilters')?.addEventListener('click',()=>{controls.search.value='';controls.category.value='all';controls.brand.value='all';controls.condition.value='all';controls.min.value='';controls.max.value='';controls.location.value='';controls.sort.value='newest';render()});document.querySelector('#filterToggle')?.addEventListener('click',e=>{const open=filters.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));if(open)filters.querySelector('input,select,button')?.focus()});document.addEventListener('ddh:localization-ready',e=>{document.querySelector('#localeChip').textContent=`${e.detail.country} · ${e.detail.currency}`;render()});load();
})();