(() => {
  'use strict';
  const cfg=window.DDH_CONFIG||{};const base=String(cfg.supabaseUrl||'').replace(/\/$/,'');const key=String(cfg.supabasePublishableKey||'');const SESSION_KEY='ddh_supabase_session';const DRAFT_KEY='ddh_sell_draft_v2';const form=document.querySelector('#listingWizard');const steps=[...document.querySelectorAll('.wizard-step')];const progress=[...document.querySelectorAll('#progress span')];const next=document.querySelector('#nextStep');const back=document.querySelector('#backStep');const submit=document.querySelector('#submitListing');const authGate=document.querySelector('#authGate');const currency=document.querySelector('#sellerCurrency');let step=0;
  const validCurrency=v=>/^[A-Z]{3}$/.test(String(v||'').toUpperCase())?String(v).toUpperCase():'';function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
  function supportedCurrencies(){try{return Intl.supportedValuesOf?.('currency')||[]}catch{return ['NGN','USD','GBP','EUR','GHS','ZAR','KES','CAD','AUD','JPY','CNY','INR','AED']}}
  function currencyOptions(){const current=validCurrency(window.DDH_LOCALIZATION?.state?.currency)||'NGN';const codes=[...new Set(supportedCurrencies())].sort();currency.innerHTML=codes.map(c=>`<option value="${c}">${c}</option>`).join('');currency.value=codes.includes(current)?current:'NGN'}
  function showStep(n){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((el,i)=>el.classList.toggle('active',i===step));progress.forEach((el,i)=>el.classList.toggle('active',i<=step));back.disabled=step===0;next.hidden=step===steps.length-1;submit.hidden=step!==steps.length-1;if(step===steps.length-1)review();window.scrollTo({top:0,behavior:'smooth'})}
  function validateCurrent(){const fields=[...steps[step].querySelectorAll('[required]')];for(const field of fields){if(!field.reportValidity())return false}return true}
  function draft(){const data={};for(const [k,v] of new FormData(form).entries()){if(!(v instanceof File))data[k]=v}try{localStorage.setItem(DRAFT_KEY,JSON.stringify(data))}catch{}}
  function restore(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d)return;for(const [k,v] of Object.entries(d)){const el=form.elements[k];if(el&&typeof v==='string')el.value=v}}catch{}}
  function review(){const d=Object.fromEntries([...new FormData(form).entries()].filter(([,v])=>!(v instanceof File)));document.querySelector('#reviewBox').innerHTML=`<strong>${d.brand||''} ${d.model||''}</strong><p style="margin:8px 0;color:#6e7480">${d.condition==='new'?'New':'Used'} · ${d.storage||'Storage not specified'} · ${d.city||'Location not specified'}</p><strong>${d.currency||''} ${Number(d.price||0).toLocaleString()}</strong>`}
  async function api(path,{method='GET',body,raw=false,contentType}={}){const s=session();if(!s?.access_token)throw new Error('Please sign in first.');const headers={apikey:key,Authorization:`Bearer ${s.access_token}`};if(body!==undefined&&!raw)headers['Content-Type']='application/json';if(contentType)headers['Content-Type']=contentType;const r=await fetch(`${base}${path}`,{method,headers,body:body===undefined?undefined:(raw?body:JSON.stringify(body))});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(data?.message||data?.error||`Request failed (${r.status})`);return data}
  async function upload(file,listingId,userId){if(!(file instanceof File)||!file.size)return;if(file.size>5*1024*1024)throw new Error('Product image must be 5 MB or smaller.');const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[file.type];if(!ext)throw new Error('Use a JPEG, PNG or WebP image.');const path=`${userId}/${listingId}/${crypto.randomUUID()}.${ext}`;await api(`/storage/v1/object/listing-images/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',body:file,raw:true,contentType:file.type});await api('/rest/v1/listing_images',{method:'POST',body:{listing_id:listingId,storage_path:path,sort_order:0}})}
  async function submitListing(e){e.preventDefault();if(!validateCurrent())return;const s=session();if(!s?.user?.id){authGate.hidden=false;form.hidden=true;return}const fd=new FormData(form);const price=Number(fd.get('price'));const cur=validCurrency(fd.get('currency'));if(!Number.isFinite(price)||price<=0||!cur)return toast('Enter a valid price and currency.');const brand=String(fd.get('brand')||'').trim(),model=String(fd.get('model')||'').trim();const country=String(fd.get('country_code')||'').trim().toUpperCase();const payload={seller_id:s.user.id,title:`${brand} ${model}`.trim(),category:String(fd.get('category')),brand,model,condition:String(fd.get('condition')),price_amount:Math.round(price*10000)/10000,price_currency:cur,price_ngn:cur==='NGN'?Math.round(price):null,storage:String(fd.get('storage')||'').trim()||null,color:String(fd.get('color')||'').trim()||null,city:String(fd.get('city')||'').trim()||null,country_code:/^[A-Z]{2}$/.test(country)?country:null,delivery_mode:String(fd.get('delivery_mode')||'pickup'),warranty_text:String(fd.get('warranty_text')||'').trim()||null,description:String(fd.get('description')||'').trim(),specs:{battery_health:String(fd.get('battery_health')||'').trim()||null,network_status:String(fd.get('network_status')||'').trim()||null,repair_history:String(fd.get('repair_history')||'').trim()||null,accessories:String(fd.get('accessories')||'').trim()||null},status:'pending'};submit.disabled=true;submit.textContent='Submitting…';try{const created=await api('/rest/v1/listings',{method:'POST',body:payload});let row=Array.isArray(created)?created[0]:created;if(!row?.id){const find=await api(`/rest/v1/listings?select=id&seller_id=eq.${encodeURIComponent(s.user.id)}&title=eq.${encodeURIComponent(payload.title)}&order=created_at.desc&limit=1`);row=find?.[0]}if(!row?.id)throw new Error('Listing was created but could not be reopened.');await upload(fd.get('image'),row.id,s.user.id);localStorage.removeItem(DRAFT_KEY);form.reset();toast('Listing submitted for review.');setTimeout(()=>location.assign('/dashboard.html'),900)}catch(err){toast(err.message)}finally{submit.disabled=false;submit.textContent='Submit for review'}}
  next.onclick=()=>{if(!validateCurrent())return;draft();showStep(step+1)};back.onclick=()=>showStep(step-1);form.addEventListener('input',draft);form.addEventListener('change',draft);form.addEventListener('submit',submitListing);document.querySelector('select[name="category"]').addEventListener('change',e=>document.querySelectorAll('.phone-spec').forEach(x=>x.hidden=e.target.value!=='Phones'));document.addEventListener('ddh:localization-ready',e=>{document.querySelector('#localeChip').textContent=`${e.detail.country} · ${e.detail.currency}`;document.querySelector('#countryCode').value=document.querySelector('#countryCode').value||e.detail.country;currencyOptions()});currencyOptions();restore();const s=session();if(!s?.user?.id){authGate.hidden=false;form.hidden=true}else{authGate.hidden=true;form.hidden=false}showStep(0);
})();