(() => {
  'use strict';
  const cfg=window.DDH_CONFIG||{};const base=String(cfg.supabaseUrl||'').replace(/\/$/,'');const key=String(cfg.supabasePublishableKey||'');const SESSION_KEY='ddh_supabase_session';const sellerId=new URLSearchParams(location.search).get('id');const grid=document.querySelector('#sellerListings');const empty=document.querySelector('#sellerEmpty');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=(a,c)=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c||'NGN',maximumFractionDigits:4}).format(Number(a)||0)}catch{return `${c||'NGN'} ${Number(a||0).toLocaleString()}`}};const imageUrl=p=>p?`${base}/storage/v1/object/public/listing-images/${String(p).split('/').map(encodeURIComponent).join('/')}`:'';
  async function get(path){const r=await fetch(`${base}${path}`,{headers:{apikey:key}});if(!r.ok)throw new Error(`Request failed (${r.status})`);return r.json()}
  const session=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}};
  function toast(t){const el=document.querySelector('#sellerToast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2500)}
  function modal(html){document.querySelector('#sellerDialogContent').innerHTML=html;document.querySelector('#sellerDialog').showModal()}
  async function writeReport(body){const s=session();if(!s?.access_token)throw new Error('Sign in to continue.');const r=await fetch(`${base}/rest/v1/reports`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||'Could not submit report.')}
  async function load(){if(!/^[0-9a-f-]{36}$/i.test(String(sellerId||''))){document.querySelector('#sellerName').textContent='Seller not found';return}try{await window.DDH_LOCALIZATION?.ready;const profiles=await get(`/rest/v1/public_profiles?select=id,display_name,created_at&id=eq.${encodeURIComponent(sellerId)}&limit=1`).catch(()=>[]);const p=profiles?.[0];document.querySelector('#sellerName').textContent=p?.display_name||'DigitalDeviceHub seller';document.querySelector('#sellerSummary').textContent='Public seller profile. Private email and account information are never shown here.';document.querySelector('#sellerFacts').innerHTML=`<div class="spec"><span>Account</span><strong>Email authenticated</strong></div>${p?.created_at?`<div class="spec"><span>Member since</span><strong>${new Date(p.created_at).toLocaleDateString(undefined,{year:'numeric',month:'long'})}</strong></div>`:''}`;const rows=await get(`/rest/v1/listings?select=id,title,category,condition,storage,city,price_amount,price_currency,created_at&seller_id=eq.${encodeURIComponent(sellerId)}&status=eq.published&order=created_at.desc&limit=60`);const ids=rows.map(x=>x.id);const imgs=new Map();if(ids.length){const list=ids.map(x=>`\"${x}\"`).join(',');const all=await get(`/rest/v1/listing_images?select=listing_id,storage_path,sort_order&listing_id=in.(${encodeURIComponent(list)})&order=sort_order.asc`).catch(()=>[]);for(const img of all){if(!imgs.has(img.listing_id))imgs.set(img.listing_id,img.storage_path)}}grid.innerHTML=rows.map(x=>`<a class="product-card" href="/device.html?id=${encodeURIComponent(x.id)}"><div class="product-image">${imgs.get(x.id)?`<img src="${esc(imageUrl(imgs.get(x.id)))}" alt="${esc(x.title)}" loading="lazy">`:'▯'}</div><div class="product-content"><div class="tag-row"><span>${esc(x.category)}</span><span class="pill">${x.condition==='new'?'New':'Used'}</span></div><h3>${esc(x.title)}</h3><div class="subline">${esc(x.storage||'Details available')}${x.city?` · ${esc(x.city)}`:''}</div><div class="seller-price-primary">${esc(money(x.price_amount,x.price_currency))}</div><div class="converted-line">Local estimate: <span class="price local-estimate" data-price-amount="${esc(x.price_amount)}" data-price-currency="${esc(x.price_currency)}">${esc(money(x.price_amount,x.price_currency))}</span></div></div></a>`).join('');empty.hidden=rows.length>0;window.DDH_LOCALIZATION?.refresh?.()}catch(err){document.querySelector('#sellerName').textContent='Seller unavailable';document.querySelector('#sellerSummary').textContent=err.message}}
  document.querySelector('#sellerDialogClose')?.addEventListener('click',()=>document.querySelector('#sellerDialog').close());
  document.querySelector('#reportSeller')?.addEventListener('click',()=>{
    const s=session();if(!s?.user?.id){location.href='/?signin=1';return}
    if(s.user.id===sellerId){toast('This is your own seller profile.');return}
    modal(`<p class="eyebrow">Report seller</p><h2>What should we review?</h2><form id="sellerReportForm"><select class="control" name="reason" required><option value="">Choose a reason</option><option value="suspected_scam">Suspected scam</option><option value="harassment">Harassment</option><option value="spam">Spam</option><option value="other">Other</option></select><textarea class="control report-notes" name="details" rows="4" maxlength="1500" placeholder="Add useful details."></textarea><button class="btn blue full-action" type="submit">Submit report</button></form>`);
    document.querySelector('#sellerReportForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await writeReport({reporter_id:s.user.id,reported_user_id:sellerId,reason:String(fd.get('reason')),details:String(fd.get('details')||'').trim()||null});document.querySelector('#sellerDialog').close();toast('Seller report submitted.')}catch(err){toast(err.message)}}
  });
  load();
})();