alter table public.listings
  add column if not exists paused_at timestamptz,
  add column if not exists sold_at timestamptz;

create table if not exists public.listing_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  visitor_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('impression','view','share')),
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  created_at timestamptz not null default now()
);

create index if not exists listing_events_listing_created_idx on public.listing_events(listing_id, created_at desc);
create index if not exists listing_events_listing_visitor_idx on public.listing_events(listing_id, visitor_id);

alter table public.listing_events enable row level security;

drop policy if exists listing_events_public_insert on public.listing_events;
create policy listing_events_public_insert on public.listing_events
for insert to anon, authenticated
with check (
  event_type in ('impression','view','share')
  and exists (
    select 1 from public.listings l
    where l.id = listing_events.listing_id and l.status = 'published'::public.listing_status
  )
  and (user_id is null or user_id = (select auth.uid()))
);

drop policy if exists listing_events_seller_read on public.listing_events;
create policy listing_events_seller_read on public.listing_events
for select to authenticated
using (
  exists (
    select 1 from public.listings l
    where l.id = listing_events.listing_id
      and (l.seller_id = (select auth.uid()) or public.is_admin())
  )
);

drop policy if exists listings_update_seller_or_admin on public.listings;
create policy listings_update_seller_or_admin on public.listings
for update to authenticated
using (
  public.is_admin()
  or (
    seller_id = (select auth.uid())
    and status in ('draft','pending','published','rejected','archived','sold','paused')
  )
)
with check (
  public.is_admin()
  or (
    seller_id = (select auth.uid())
    and status in ('draft','pending','published','archived','sold','paused')
  )
);
